apiVersion: apps/v1
kind: Deployment
metadata:
  name: birthdaybot
spec:
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: birthdaybot
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: birthdaybot
    spec:
      containers:
      - image: gcr.io/gcp-project/birthdaybot:1.0
        imagePullPolicy: Always
        name: birthdaybot
        env:
        - name: BDB_DB_USER
          value: bbotdbuser
        - name: BDB_DB_PASS
          value: bbotdbpass
        - name: BDB_DB_NAME
          value: bbotdb
        - name: BDB_DB_HOST
          value: gcp-cloudsql
        - name: BDB_DB_PORT
          value: '3306'
